services:
  - type: web
    name: db-proxy-for-grandma
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TARGET_URL
        value: "http://www.jieyoutsg.com/e/member/login/"  # 替换成您的数据库网站
      - key: ALLOWED_EMAILS
        value: "386495297@qq.com,18504755335@163.com,同事3@gmail.com"  # 同事的邮箱
    healthCheckPath: /health
    autoDeploy: true
